### ISSUE TITLE
create a compact pull-quote variation

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1108]
## Is this a proposal or an amendment?

- Amendment

.p-pull-quotes

## Visual

Provide a screenshot or link to prototype of your pattern proposal.

## Context

* often pull quotes are put in three column layouts, we need a smaller version to work in this scenerio

## State

I think it should be called `.is-compact`

## Progressive enhancement

sample code

```scss
  .p-pull-quote.is-compact,
  .p-pull-quote--accent.is-compact {
    > p {
      @include heading-5;

      &:first-of-type::before,
      &:last-of-type::after {
        font-size: $sp-large;

        @media (min-width: $breakpoint-medium) {
          font-size: $sp-xx-large;
        }

        @media (min-width: $breakpoint-large) {
          font-size: $sp-xx-large;
        }
      }
    }

    .p-pull-quote__citation {
      font-size: 1.1rem;
      line-height: 1.15;
      margin-top: 2rem;
    }
  }
```

![image](https://user-images.githubusercontent.com/441217/26993189-e6d53fb0-4d59-11e7-9781-0ace24e0b3fd.png)
