### ISSUE TITLE
sup is too high

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1109]
## Process

1. The default `<sup>` renders too high and the text too small

![image](https://user-images.githubusercontent.com/441217/27003819-d9a24224-4df5-11e7-836d-5b159e71ad67.png)

## Expected result

* should be more like

```scss
sup {
  font-size: .75em;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}
```

![image](https://user-images.githubusercontent.com/441217/27003878-30a8d7d0-4df7-11e7-9b26-2b5dd7e5d398.png)

and 

![image](https://user-images.githubusercontent.com/441217/27003881-3c1b589a-4df7-11e7-97cc-f522bd3aacfe.png)
