### ISSUE TITLE
fieldset should be dark with .p-strip--dark/accent (vbt)

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1113]
## Process

1. create a form in a dark or accent strip
2. see that the fieldset is still light

## Expected result

You shouldn't see a light border around the form.

Fix on ubuntu.com

```scss
  .p-strip--accent,
  .p-strip--dark {
    @extend %strip--accent;

    fieldset {
      background-color: $color-accent;
      border-color: $color-accent;
    }
  }
```
