### ISSUE TITLE
Importing 'vanilla' without calling any mixins outputs grid CSS

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1137]
## Process

I'm trying to build single modules from vanilla, but importing 'vanilla' alone without calling any pattern mixins renders grid CSS.

```scss
@import './node_modules/vanilla-framework/scss/_vanilla.scss'
```

## Expected result

Should result in empty CSS.
If any pattern mixins are called only result of these mixins should be visible in CSS.

## Current result

Result CSS contains grid CSS:

```css
/*
SHELVES
-------

The only responsive, fluid CSS grid with infinitely nestable columns.

Copyright (c) 2012, Pete Browne
*/
[grid-demo] [class*="col-"] {
  background: #cdcdcd;
  margin-bottom: 1rem; }

/*
SHELVES
-------

The only responsive, fluid CSS grid with infinitely nestable columns.

Copyright (c) 2012, Pete Browne
*/
[grid-demo] [class*="col-"] {
  background: #cdcdcd;
  margin-bottom: 1rem; }

@media screen and (max-width: 400px) {
  @-ms-viewport {
    width: 320px; } }

img {
  max-width: 100%;
  height: auto; }
  @media \0screen {
    img {
      width: auto; } }

/* ... and more ... */
```
