### ISSUE TITLE
Cross linking p-strip and p-link--external

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1378]
It seems we set:
```css
.p-strip .p-link--external {
    color: $color-link;
}
```

This overrides button color when using external links in buttons.

To test add the following to an example:
```html
<div class="p-strip">
  <a href="https://jujucharms.com/jaas" class="p-button--brand">
    <span class="p-link--external">Try the JAAS beta today</span>
  </a>
</div>
```
