### ISSUE TITLE
fieldset is missing border per design

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1906]
according to the design, the fieldset should have a border with a border radius... somehow that is missing.

``` css
fieldset {
  border: 1px solid $color-light;
  border-radius: $sp-xx-small;
}
```
