### ISSUE TITLE
Blockquote spacing is messed up

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1988]
This is what blockquotes look like by default:

![blockquote-spacing](https://user-images.githubusercontent.com/519935/45614881-3946ac00-ba6b-11e8-9798-fc51d46d7744.png)

A small CSS fix:

``` css
blockquote {
  & > :last-child {
    margin-bottom: 0;
  }

  padding-bottom: 0.4rem;
  margin-bottom: 1.1rem;
}
```

And it looks like this:

![blockquote-better](https://user-images.githubusercontent.com/519935/45614956-6dba6800-ba6b-11e8-8810-8ef358308809.png)

Aaaaah much better.
