### ISSUE TITLE
Why margin-top: -1.1rem on p + p:not(.p-muted-heading)?

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#2019]
Basically paragraphs next to other paragraphs have `margin-top: -1.1rem`. This makes `<p>` elements interact very weirdly next to other empty `<p>` elements.

Why do they have this? Could it be removed? Otherwise, could we add:

``` scss
p:empty + p:not(.p-muted-heading), p + p:not(.p-muted-heading):empty, p:empty + p:not(.p-muted-heading):empty {
  margin-top: 0;
}
```

(Like I did here https://github.com/canonical-websites/discourse-docs.snapcraft.io/pull/42/files#diff-9f40d64fd95564c5ba27a3ef536cb50fR87 )
