### ISSUE TITLE
Add accessibility override to reduce motion

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#2116]
Some people with vertigo, epilepsy etc can change a setting in their OS to reduce or remove visual motions.

We can now specify this via a media query:

```css
@media (prefers-reduced-motion: reduce) { 
 * { 
   animation: none !important;
   transition: none !important; 
  } 
 }
```

Browser support is [patchy](https://caniuse.com/#feat=prefers-reduced-motion) but iOS supports it and everything else will just ignore it, progressive enhancement FTW.

I think we should add this to the base of Vanilla?
