### ISSUE TITLE
Add inline ES5 to add javascript functionality

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#619]
## Is this a proposal or an amendment?
- Proposal
## Context

As we are asking users to copy and paste snippets of mark up then we could include js inline. This might sound yucky at first but it would allow us to provide copy and paste functionality without dealing with including scripts and namespace clobbering. Also as the functionality would be very simple it would not need testing infrastructure. Allowing us to focus our time on the scss which is important.

Example:

``` html
<a class="navigation-toggle" onClick="this.classList.toggle('is-open')">Menu</a>
<ul class="navigation">
    ...
</ul>
```

``` scss
.navigation-toggle > .navigation {
    display: none;
}

.navigation-toggle.is-open > .navigation {
    display: block;
}
```
## Progressive enhancement

We can state these functionality is only compatible with IE8+ and if you need lower support please develop there own JS.
